export const sitemapPaths = [
	'/',
	'/pricing',
	'/contact',
	'/about',
	'/login',
	'/register',
	'/forgot-password',
	'/terms-of-service',
	'/privacy-policy',
	'/affiliate',
	'/tools',
	'/merge-pdf',
	'/compress-pdf',
	'/split-pdf',
	'/pdf-to-word',
]
